import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:startlink/features/ai_insights/domain/entities/ai_insight.dart';
import 'package:startlink/features/ai_insights/presentation/bloc/ai_insight_bloc.dart';
import 'package:startlink/features/auth/domain/repository/auth_repository.dart';

class AIInsightCard extends StatelessWidget {
  final String ideaId;

  const AIInsightCard({super.key, required this.ideaId});

  @override
  Widget build(BuildContext context) {
    // Current Investor ID
    final investorId = context.read<AuthRepository>().currentUser?.id ?? '';

    // Trigger Fetch
    context.read<AIInsightBloc>().add(
      FetchAIInsight(ideaId: ideaId, investorId: investorId),
    );

    return BlocBuilder<AIInsightBloc, AIInsightState>(
      builder: (context, state) {
        if (state is AIInsightLoading) {
          // Shimmer or small loader
          return Container(
            height: 100,
            width: double.infinity,
            alignment: Alignment.center,
            margin: const EdgeInsets.only(bottom: 24),
            decoration: BoxDecoration(
              color: Theme.of(
                context,
              ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.3),
              borderRadius: BorderRadius.circular(16),
            ),
            child: const CircularProgressIndicator(),
          );
        }

        if (state is AIInsightUnavailable || state is AIInsightError) {
          // Show Analyze Button for manual trigger
          return Container(
            margin: const EdgeInsets.only(bottom: 24),
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.surface,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.grey.withValues(alpha: 0.2)),
            ),
            child: Column(
              children: [
                const Icon(Icons.auto_awesome, size: 32, color: Colors.purple),
                const SizedBox(height: 12),
                const Text(
                  'AI Investment Analysis',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                Text(
                  'Get an instant investment snapshot, strengths, and risks analysis.',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.grey[600], fontSize: 12),
                ),
                const SizedBox(height: 16),
                ElevatedButton.icon(
                  onPressed: () {
                    context.read<AIInsightBloc>().add(
                      TriggerAIAnalysis(
                        ideaId: ideaId,
                        investorId:
                            context.read<AuthRepository>().currentUser?.id ??
                            '',
                      ),
                    );
                  },
                  icon: const Icon(Icons.bolt),
                  label: const Text('Generate Insights'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.purple,
                    foregroundColor: Colors.white,
                  ),
                ),
              ],
            ),
          );
        }

        if (state is AIInsightLoaded) {
          return _buildInsightContent(context, state.insight);
        }

        return const SizedBox.shrink();
      },
    );
  }

  Widget _buildInsightContent(BuildContext context, AIInsight insight) {
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 24),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.purple.withValues(alpha: 0.3)), // AI Theme
        boxShadow: [
          BoxShadow(
            color: Colors.purple.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              Icon(Icons.psychology, color: Colors.purple.shade400),
              const SizedBox(width: 8),
              Text(
                'AI Analysis',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                  color: Colors.purple.shade700,
                ),
              ),
              const Spacer(),
              Tooltip(
                message:
                    'Generated by AI as decision support. Not financial advice.',
                triggerMode: TooltipTriggerMode.tap,
                child: Icon(
                  Icons.info_outline,
                  size: 16,
                  color: Colors.grey.shade400,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Snapshot Signals
          Row(
            children: [
              _buildSignalChip(context, 'Market', insight.marketPotential),
              const SizedBox(width: 8),
              _buildSignalChip(
                context,
                'Execution',
                insight.executionRisk,
                isRisk: true,
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Summary
          if (insight.summary != null) ...[
            Text(
              insight.summary!,
              style: Theme.of(
                context,
              ).textTheme.bodyMedium?.copyWith(height: 1.5),
            ),
            const SizedBox(height: 16),
          ],

          // Collapsible Strengths & Risks
          _buildExpandableSection(
            context,
            'Strengths',
            insight.strengths,
            Colors.green,
          ),
          _buildExpandableSection(
            context,
            'Risks',
            insight.risks,
            Colors.orange,
          ),

          if ((insight.personalFitScore ?? 0) > 0) ...[
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.purple.withValues(alpha: 0.05),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Match For You: ${insight.personalFitScore}%',
                    style: const TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.purple,
                    ),
                  ),
                  if (insight.fitReasons != null)
                    ...insight.fitReasons!.map(
                      (r) => Padding(
                        padding: const EdgeInsets.only(top: 4),
                        child: Row(
                          children: [
                            const Icon(
                              Icons.check,
                              size: 12,
                              color: Colors.purple,
                            ),
                            const SizedBox(width: 4),
                            Expanded(
                              child: Text(
                                r,
                                style: Theme.of(context).textTheme.bodySmall,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                ],
              ),
            ),
          ],

          const SizedBox(height: 8),
          Center(
            child: Text(
              'AI insights are supportive signals, not financial advice.',
              style: Theme.of(
                context,
              ).textTheme.bodySmall?.copyWith(fontSize: 10, color: Colors.grey),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSignalChip(
    BuildContext context,
    String label,
    String value, {
    bool isRisk = false,
  }) {
    Color color = Colors.grey;
    if (value == 'High') color = isRisk ? Colors.red : Colors.green;
    if (value == 'Medium') color = Colors.orange;
    if (value == 'Low') {
      color = isRisk
          ? Colors.green
          : Colors
                .red; // Low risk is good (green), Low potential is bad (red) - wait, low potential red. Correct.
    }

    // Correction: Low Exposure Risk is Green. Low Market Potential is Red.
    // My logic above:
    // value=High, isRisk=F -> Green (High Market Potential) -> Correct
    // value=High, isRisk=T -> Red (High Execution Risk) -> Correct
    // value=Low, isRisk=F -> Red (Low Market Potential) -> Correct
    // value=Low, isRisk=T -> Green (Low Execution Risk) -> Correct

    return Expanded(
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.1),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Column(
          children: [
            Text(
              label.toUpperCase(),
              style: TextStyle(
                fontSize: 10,
                color: Colors.grey.shade600,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 2),
            Text(
              value,
              style: TextStyle(fontWeight: FontWeight.bold, color: color),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildExpandableSection(
    BuildContext context,
    String title,
    List<String> items,
    Color color,
  ) {
    if (items.isEmpty) return const SizedBox.shrink();
    return ExpansionTile(
      title: Text(
        title,
        style: TextStyle(color: color, fontWeight: FontWeight.bold),
      ),
      leading: Icon(
        title == 'Strengths' ? Icons.trending_up : Icons.warning_amber,
        color: color,
      ),
      childrenPadding: const EdgeInsets.only(bottom: 12, left: 16, right: 16),
      dense: true,
      children: items
          .map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 4),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '• ',
                    style: TextStyle(color: color, fontWeight: FontWeight.bold),
                  ),
                  Expanded(child: Text(item)),
                ],
              ),
            ),
          )
          .toList(),
    );
  }
}
