// lib/features/messaging/data/models/message_model.dart

class MessageModel {
  final String id;
  final String senderId;
  final String receiverId;
  final String ideaId;
  final String content;
  final bool isRead;
  final DateTime createdAt;

  const MessageModel({
    required this.id,
    required this.senderId,
    required this.receiverId,
    required this.ideaId,
    required this.content,
    required this.isRead,
    required this.createdAt,
  });

  factory MessageModel.fromJson(Map<String, dynamic> json) {
    return MessageModel(
      id: json['id'] as String,
      senderId: json['sender_id'] as String,
      receiverId: json['receiver_id'] as String,
      ideaId: json['idea_id'] as String,
      content: json['content'] as String,
      isRead: (json['is_read'] as bool?) ?? false,
      // Convert to local time for display
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
    );
  }

  /// Used when inserting — id and created_at are generated by Postgres
  Map<String, dynamic> toInsertJson() => {
    'sender_id': senderId,
    'receiver_id': receiverId,
    'idea_id': ideaId,
    'content': content,
  };

  MessageModel copyWith({bool? isRead}) {
    return MessageModel(
      id: id,
      senderId: senderId,
      receiverId: receiverId,
      ideaId: ideaId,
      content: content,
      isRead: isRead ?? this.isRead,
      createdAt: createdAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || (other is MessageModel && other.id == id);

  @override
  int get hashCode => id.hashCode;
}
