import 'package:startlink/features/matching/domain/entities/idea_match.dart';
import 'package:startlink/features/profile/data/models/profile_model.dart';

class IdeaMatchModel extends IdeaMatch {
  const IdeaMatchModel({
    required super.id,
    required super.ideaId,
    required super.matchedProfileId,
    required super.matchedProfileName,
    super.matchedProfileAvatarUrl,
    required super.role,
    required super.matchScore,
    required super.matchReason,
  });

  factory IdeaMatchModel.fromJson(Map<String, dynamic> json) {
    // Handling joined profile data if available
    final profileData = json['profiles'] as Map<String, dynamic>?;

    return IdeaMatchModel(
      id: json['id'] as String,
      ideaId: json['idea_id'] as String,
      matchedProfileId: json['matched_profile_id'] as String,
      matchedProfileName: profileData?['full_name'] ?? 'Unknown User',
      matchedProfileAvatarUrl: profileData?['avatar_url'],
      role: json['role'] as String,
      matchScore: json['match_score'] as int,
      matchReason: json['match_reason'] as Map<String, dynamic>? ?? {},
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'idea_id': ideaId,
      'matched_profile_id': matchedProfileId,
      'role': role,
      'match_score': matchScore,
      'match_reason': matchReason,
    };
  }

  // Helper to create model from calculation results + profile
  factory IdeaMatchModel.fromCalculation(
    String ideaId,
    ProfileModel profile,
    String role,
    int score,
    Map<String, dynamic> reason,
  ) {
    return IdeaMatchModel(
      id: '', // Will be generated by DB
      ideaId: ideaId,
      matchedProfileId: profile.id,
      matchedProfileName: profile.fullName ?? 'Unknown',
      matchedProfileAvatarUrl: profile.avatarUrl,
      role: role,
      matchScore: score,
      matchReason: reason,
    );
  }
}
