import 'package:startlink/features/compass/data/models/compass_recommendation_model.dart';
import 'package:startlink/features/idea/domain/entities/idea.dart';
import 'package:startlink/features/profile/data/models/profile_model.dart';

class CompassRuleEngine {
  static List<CompassRecommendationModel> evaluate(
    ProfileModel profile,
    List<Idea>? ideas,
  ) {
    final List<CompassRecommendationModel> recs = [];
    final role = profile.role ?? 'Innovator';

    // 1. Profile Checks (Universal)
    if (profile.profileCompletion < 70) {
      // Find missing critical pieces
      if (profile.skills.isEmpty) {
        recs.add(
          _createRec(
            profile.id,
            role,
            'add_skills',
            'Add your top 3 skills',
            'Helps collaborators find you.',
            {'aura': 15, 'trust': 5},
            90,
          ),
        );
      }
      if (profile.about == null || profile.about!.isEmpty) {
        recs.add(
          _createRec(
            profile.id,
            role,
            'add_about',
            'Tell your story',
            'Investors connect with personal stories.',
            {'aura': 10, 'trust': 10},
            80,
          ),
        );
      }
    }

    // 2. Role Specific: Innovator
    if (role == 'Innovator') {
      if (ideas == null || ideas.isEmpty) {
        recs.add(
          _createRec(
            profile.id,
            role,
            'create_first_idea',
            'Draft your first idea',
            'Start your journey. It remains private until you publish.',
            {'confidence': 20, 'aura': 50},
            100,
          ),
        );
      } else {
        // Check Idea Health
        for (var idea in ideas) {
          if (idea.status == 'Draft') {
            recs.add(
              _createRec(
                profile.id,
                role,
                'publish_idea',
                'Publish "${idea.title}"',
                'Get feedback from mentors.',
                {'confidence': 10, 'aura': 30},
                95,
              ),
            );
          }
          if (idea.problemStatement.length < 50) {
            recs.add(
              _createRec(
                profile.id,
                role,
                'clarify_problem',
                'Improve Problem Clarity',
                'Mentors flagged unclear market pain in "${idea.title}".',
                {'confidence': 12},
                85,
              ),
            );
          }
        }
      }
    }

    // 3. Social / Verification
    if (profile.linkedinUrl == null || profile.linkedinUrl!.isEmpty) {
      recs.add(
        _createRec(
          profile.id,
          role,
          'link_linkedin',
          'Add LinkedIn to profile',
          'Investors prefer verified founders.',
          {'aura': 20, 'trust': 15},
          60,
        ),
      );
    }

    // Sort by priority descending
    recs.sort((a, b) => b.priority.compareTo(a.priority));

    return recs.take(3).toList(); // Return top 3
  }

  static CompassRecommendationModel _createRec(
    String profileId,
    String role,
    String key,
    String title,
    String desc,
    Map<String, dynamic> output,
    int priority,
  ) {
    return CompassRecommendationModel(
      id: '', // Generated by DB
      profileId: profileId,
      role: role,
      actionKey: key,
      title: title,
      description: desc,
      expectedBenefit: output,
      priority: priority,
    );
  }
}
